### ISSUE TITLE
KeyVault-yaml-secret Warning

### ISSUE THREAD

**Issue by sfawcett123** [DFE-Digital/github-actions#34]
When the secret value is empty we see a warning in our workflows:

`Can't add secret mask for empty string in ##[add-mask] command.`

This happens because we use the same deployment method to deploy development and production, but in production we do not set a value in the YAML.

**Comment by saliceti** [comment]
Shall we add a conditional here? https://github.com/DFE-Digital/github-actions/blob/master/keyvault-yaml-secret/action.yml#L33

**Comment by saliceti** [comment]
The action is being depracated
Closing
